### ISSUE TITLE
New CS:GO update

### ISSUE THREAD

**Issue by notradger** [aixxe/Chameleon#1]
I guess the new CS:GO update breaks this.. Thought you'd like to know.. Thanks..

**Comment by aixxe** [comment]
Should be fixed now. A few NetVar offsets and FireEventClientSide changed. The current solution isn't ideal but it'll work until I have time to look into the new update properly.

**Comment by notradger** [comment]
Awesome.. Doesn't crash cs:go anymore.. 

But one small thing I did notice was the knife models i don't think are being loaded right.. (not sure if thats the right way to put it) 

Maybe its something with "inline void SetModelConfig();"  in [skins.h] or... ??

I included a snapshot of me on the terrorist side .. Should be a bowie knife?
[Screenshot](http://imgur.com/a/HiNaL)

Good job on the whole project tho :-)

**Comment by aixxe** [comment]
Please test the latest commit and let me know if it still doesn't work.

**Comment by notradger** [comment]
Good deal axxie.. You the man bro :) Works great..
