### ISSUE TITLE
Knife models doesn't work properly

### ISSUE THREAD

**Issue by kapiwulon** [aixxe/Chameleon#2]
http://images.akamai.steamusercontent.com/ugc/250339036807117635/6207157095F33902415655C8CC2DD0422AFD7032/

On bots it works fine, but on any online server its bugged as u can see on screenshot

**Comment by aixxe** [comment]
Please test the latest commit and let me know if it still doesn't work.

**Comment by kapiwulon** [comment]
Yes. It works perfectly fine now. Thanks for bugfix :)

**Comment by kapiwulon** [comment]
worked once, now broken again... xd

**Comment by kapiwulon** [comment]
after FireEventClientSide.h Back to using game_newmap event for reloading model indexes update started working. ty m8
