### ISSUE TITLE
Replacing non-default knife

### ISSUE THREAD

**Issue by toxiicdev** [aixxe/Chameleon#5]
Hello aixxe, how can I get the 'in-use' knife slot where to replace the model?

Is there a way to this?

Example I got a flip knife, and I want to make that it automatically detects that I got a flip knife and replaces that.. how could I do it?

**Comment by thepapanoob** [comment]
just remove the check for the default knifes and replace every knife!

**Comment by toxiicdev** [comment]
@Kruemmelmonster thats was my idea too.. thats why I was asking if there is any way to avoid that.

**Comment by toxiicdev** [comment]
Did it
