### ISSUE TITLE
Knife Skins

### ISSUE THREAD

**Issue by notradger** [aixxe/Chameleon#6]
Well I guess the new update changed something once again..  The knife skins don't work.. 

Whats weird is the actual knife type changes.. But the skin for it doesn't.. It ends up looking like a vanilla knife.. I did notice messages in the console:

Here is a screenshot: [Screenshot of knife](http://steamcommunity.com/sharedfiles/filedetails/?id=810773072)
**Failed to set custom material for 'karam', no matching material name found on model models/weapons/v_knife_default_ct.mdl**

Thanks Axxie for your contribution. :)

**Comment by aixxe** [comment]
Yeah, I already know about this. Still haven't got around to fixing it yet but there are solutions posted around on forums and other projects to look at in the meantime.

**Comment by aixxe** [comment]
Should be fixed now, comment if it's still not working and I'll reopen the issue.
