### ISSUE TITLE
Safe?

### ISSUE THREAD

**Issue by EzYDark** [aixxe/Chameleon#7]
Hi. It's safe this skin changer? It's rly nice changer. :) I play only on insecure server. I'm scared about VAC ban.

**Comment by aixxe** [comment]
It's safe to use on insecure servers, yes.

**Comment by EzYDark** [comment]
But it's safe on VAC servers and MM?

**Comment by aixxe** [comment]
Unless you have made significant changes to the source code to bypass signature detection, that is unlikely.
